
import = ["~/.config/alacritty/catppuccin-mocha.toml"]
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 10

[font.normal]
#family = "CaskaydiaCove Nerd Font"
family = "JetbrainsMono Nerd Font"

[font.bold]
#family = "CaskaydiaCove Nerd Font"
family = "JetbrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
#family = "CaskaydiaCove Nerd Font"
family = "JetbrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
#family = "JetbrainsMono Nerd Font"
family = "JetbrainsMono Nerd Font"
style = "Italic"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false

[shell]
program = "/usr/bin/zsh"

[window]
padding = { x = 0, y = 0 }
opacity = 0.90

#[window.class]
#general = "Alacritty"
#instance = "Alacritty"

[cursor]
style = { shape = "Underline", blinking = "On" }

